"use strict";
exports.__esModule = true;
var organizations = [
    {
        account_plan: {
            createddate: 2023 - 01 - 18,
            updateddate: 2023 - 01 - 18,
            deletedat: "NULL",
            id: "cca85c84-4724-49fd-8ff2-3917bf83cba9",
            shopifyid: "NULL",
            uniqueshopifyid: "NULL",
            receivedfromshopifydate: 2023 - 01 - 18, T18: 25, 23.000: Z,
            shopifyupdatedate: 2023 - 01 - 18, T18: 25, 23.000: Z,
            planname: "Free Trial",
            status: "ACTIVE",
            approvedat: "NULL",
            trialdays: 14,
            usagelineitemshopifyid: "NULL",
            planfee: 0,
            transactionfee: 0,
            percentagefee: 0,
            organizationid: "adc50e61-6072-410e-9936-162ce46982ce",
            features: "{\"CORE_SUBSCRIPTIONS\":true,\"CORE_CONFIGURATION\":true,\"ANALYTICS\":true,\"LOOKER_ANALYTICS\":false,\"SHOPIFY_DEBUG\":false,\"RETENTION\":true,\"INTEGRATIONS\":true,\"PREPAID_SELLING_PLAN\":false,\"SEQUENTIAL_SELLING_PLAN\":true,\"ADVANCED_SEQUENTIAL_SELLING_PLAN\":false,\"SETUP\":false,\"LOYALTY\":false,\"BUNDLES\":false,\"TRANSLATIONS\":false,\"PASSWORDLESS\":false,\"TRENDING\":false}",
            confirmationurl: "NULL",
            trialperiodstart: 2023 - 01 - 18, T18: 25, 23.000: Z,
            trialperiodend: 2023 - 02 - 01, T18: 25, 23.000: Z,
            reportusageat: "NULL",
            is_canceled: function () {
                return this.status === "CANCELLED";
            }
        },
        account_plan: {
            createddate: 2023 - 01 - 20, T00: 17, 01: .764,
            Z: Z,
            updateddate: 2023 - 01 - 20, T00: 17, 01: .764,
            Z: Z,
            deletedat: "NULL",
            id: "af071cb8-abc5-4dfa-ba2e-2cf930447587",
            shopifyid: "NULL",
            uniqueshopifyid: "NULL",
            receivedfromshopifydate: 2023 - 01 - 20, T00: 17, 01: .000,
            Z: Z,
            shopifyupdatedate: 2023 - 01 - 20, T00: 17, 01: .000,
            Z: Z,
            planname: "Excel",
            status: "ACTIVE",
            approvedat: "NULL",
            trialdays: 14,
            usagelineitemshopifyid: "NULL",
            planfee: 0,
            transactionfee: 0,
            percentagefee: 0,
            organizationid: "75f223ec-2ede-4b38-9096-f9333d4141c7",
            features: "{\"CORE_CONFIGURATION\":true,\"CORE_SUBSCRIPTIONS\":true,\"LOOKER_ANALYTICS\":true,\"RETENTION\":true,\"INTEGRATIONS\":true,\"PREPAID_SELLING_PLAN\":true,\"SEQUENTIAL_SELLING_PLAN\":true,\"MIGRATIONS\":true,\"BUNDLES\":true,\"LOYALTY\":true,\"TRANSLATIONS\":true,\"PASSWORDLESS\": true}\n",
            confirmationurl: "NULL",
            trialperiodstart: 2023 - 01 - 20, T00: 17, 01: .000,
            Z: Z,
            trialperiodend: 2023 - 02 - 03, T00: 17, 01: .000,
            Z: Z,
            reportusageat: "NULL",
            is_cancelled: function () {
                return this.status === "CANCELLED";
            }
        },
        account_plan: {
            createddate: 2023 - 01 - 20, T04: 07, 20.251: Z,
            updateddate: 2023 - 01 - 20, T04: 07, 20.251: Z,
            deletedat: "NULL",
            id: "05078458-d1c4-4221-b702-057c33f7e8ee",
            shopifyid: "NULL",
            uniqueshopifyid: "NULL",
            receivedfromshopifydate: 2023 - 01 - 20, T04: 07, 20.000: Z,
            shopifyupdatedate: 2023 - 01 - 20, T04: 07, 20.000: Z,
            planname: "Free Trial",
            status: "ACTIVE",
            approvedat: "NULL",
            trialdays: 14,
            usagelineitemshopifyid: "NULL",
            planfee: 0,
            transactionfee: 0,
            percentagefee: 0,
            organizationid: "cce0223a-fcac-4953-9137-3c5c10c158c3",
            features: "{\"CORE_SUBSCRIPTIONS\":true,\"CORE_CONFIGURATION\":true,\"ANALYTICS\":true,\"LOOKER_ANALYTICS\":false,\"SHOPIFY_DEBUG\":false,\"RETENTION\":true,\"INTEGRATIONS\":true,\"PREPAID_SELLING_PLAN\":false,\"SEQUENTIAL_SELLING_PLAN\":true,\"ADVANCED_SEQUENTIAL_SELLING_PLAN\":false,\"SETUP\":false,\"LOYALTY\":false,\"BUNDLES\":false,\"TRANSLATIONS\":false,\"PASSWORDLESS\":false,\"TRENDING\":false}",
            confirmationurl: "NULL",
            trialperiodstart: 2023 - 01 - 20, T04: 07, 20.000: Z,
            trialperiodend: 2023 - 02 - 03, T04: 07, 20.000: Z,
            reportusageat: "NULL",
            is_cancelled: function () {
                return this.status === "CANCELLED";
            }
        },
        account_plan: {
            createddate: 2023 - 01 - 18, T21: 42, 39.372: Z,
            updateddate: 2023 - 01 - 18, T21: 42, 39.372: Z,
            deletedat: "NULL",
            id: "e91e2145-aaef-4e6c-996d-8efd7f75f11c",
            shopifyid: "NULL",
            uniqueshopifyid: "NULL",
            receivedfromshopifydate: 2023 - 01 - 18, T21: 42, 39.000: Z,
            shopifyupdatedate: 2023 - 01 - 18, T21: 42, 39.000: Z,
            planname: "Free Trial",
            status: "ACTIVE",
            approvedat: "NULL",
            trialdays: 14,
            usagelineitemshopifyid: "NULL",
            planfee: 0,
            transactionfee: 0,
            percentagefee: 0,
            organizationid: "788f31b6-1418-452e-9064-28041319523d",
            features: "{\"CORE_SUBSCRIPTIONS\":true,\"CORE_CONFIGURATION\":true,\"ANALYTICS\":true,\"LOOKER_ANALYTICS\":false,\"SHOPIFY_DEBUG\":false,\"RETENTION\":true,\"INTEGRATIONS\":true,\"PREPAID_SELLING_PLAN\":false,\"SEQUENTIAL_SELLING_PLAN\":true,\"ADVANCED_SEQUENTIAL_SELLING_PLAN\":false,\"SETUP\":false,\"LOYALTY\":false,\"BUNDLES\":false,\"TRANSLATIONS\":false,\"PASSWORDLESS\":false,\"TRENDING\":false}",
            confirmationurl: "NULL",
            trialperiodstart: 2023 - 01 - 18, T21: 42, 39.000: Z,
            trialperiodend: 2023 - 02 - 01, T21: 42, 39.000: Z,
            reportusageat: "NULL",
            is_cancelled: function () {
                return this.status === "CANCELLED";
            }
        },
        account_plan: {
            createddate: 2023 - 01 - 19, T04: 55, 25.063: Z,
            updateddate: 2023 - 01 - 19, T04: 55, 25.063: Z,
            deletedat: "NULL",
            id: "5ef30cf7-50ce-4456-88c7-218b47588515",
            shopifyid: "NULL",
            uniqueshopifyid: "NULL",
            receivedfromshopifydate: 2023 - 01 - 19, T04: 55, 25.000: Z,
            shopifyupdatedate: 2023 - 01 - 19, T04: 55, 25.000: Z,
            planname: "Free Trial",
            status: "ACTIVE",
            approvedat: "NULL",
            trialdays: 14,
            usagelineitemshopifyid: "NULL",
            planfee: 0,
            transactionfee: 0,
            percentagefee: 0,
            organizationid: "53980994-173e-4620-b560-2c2c437953ec",
            features: "{\"CORE_SUBSCRIPTIONS\":true,\"CORE_CONFIGURATION\":true,\"ANALYTICS\":true,\"LOOKER_ANALYTICS\":false,\"SHOPIFY_DEBUG\":false,\"RETENTION\":true,\"INTEGRATIONS\":true,\"PREPAID_SELLING_PLAN\":false,\"SEQUENTIAL_SELLING_PLAN\":true,\"ADVANCED_SEQUENTIAL_SELLING_PLAN\":false,\"SETUP\":false,\"LOYALTY\":false,\"BUNDLES\":false,\"TRANSLATIONS\":false,\"PASSWORDLESS\":false,\"TRENDING\":false}",
            confirmationurl: "NULL",
            trialperiodstart: 2023 - 01 - 19, T04: 55, 25.000: Z,
            trialperiodend: 2023 - 02 - 02, T04: 55, 25.000: Z,
            reportusageat: "NULL",
            is_cancelled: function () {
                return this.status === "CANCELLED";
            }
        },
        account_plan: {
            createddate: 2023 - 01 - 19, T01: 54, 32.393: Z,
            updateddate: 2023 - 01 - 19, T14: 57, 04: .703,
            Z: Z,
            deletedat: "NULL",
            id: "8217d6fb-911f-4da4-be35-e8cbf091fb62",
            shopifyid: "NULL",
            uniqueshopifyid: "NULL",
            receivedfromshopifydate: 2023 - 01 - 19, T01: 54, 32.000: Z,
            shopifyupdatedate: 2023 - 01 - 19, T01: 54, 32.000: Z,
            planname: "Free Trial",
            status: "CANCELLED",
            approvedat: "NULL",
            trialdays: 14,
            usagelineitemshopifyid: "NULL",
            planfee: 0,
            transactionfee: 0,
            percentagefee: 0,
            organizationid: "c535b056-fe20-4409-ab16-a4b7c5e7dff6",
            features: "{\"CORE_SUBSCRIPTIONS\":true,\"CORE_CONFIGURATION\":true,\"ANALYTICS\":true,\"LOOKER_ANALYTICS\":false,\"SHOPIFY_DEBUG\":false,\"RETENTION\":true,\"INTEGRATIONS\":true,\"PREPAID_SELLING_PLAN\":false,\"SEQUENTIAL_SELLING_PLAN\":true,\"ADVANCED_SEQUENTIAL_SELLING_PLAN\":false,\"SETUP\":false,\"LOYALTY\":false,\"BUNDLES\":false,\"TRANSLATIONS\":false,\"PASSWORDLESS\":false,\"TRENDING\":false}",
            confirmationurl: "NULL",
            trialperiodstart: 2023 - 01 - 19, T01: 54, 32.000: Z,
            trialperiodend: 2023 - 02 - 02, T01: 54, 32.000: Z,
            reportusageat: "NULL",
            is_cancelled: function () {
                return this.status === "CANCELLED";
            }
        },
        account_plan: {
            createddate: 2023 - 01 - 18, T14: 29, 25.821: Z,
            updateddate: 2023 - 01 - 18, T14: 29, 25.821: Z,
            deletedat: "NULL",
            id: "04eceded-2972-46f0-ac24-b69745ddcb95",
            shopifyid: "NULL",
            uniqueshopifyid: "NULL",
            receivedfromshopifydate: 2023 - 01 - 18, T14: 29, 25.000: Z,
            shopifyupdatedate: 2023 - 01 - 18, T14: 29, 25.000: Z,
            planname: "Free Trial",
            status: "ACTIVE",
            approvedat: "NULL",
            trialdays: 14,
            usagelineitemshopifyid: "NULL",
            planfee: 0,
            transactionfee: 0,
            percentagefee: 0,
            organizationid: "8533ba30-ad82-41e6-9825-af3c2122d95f",
            features: "{\"CORE_SUBSCRIPTIONS\":true,\"CORE_CONFIGURATION\":true,\"ANALYTICS\":true,\"LOOKER_ANALYTICS\":false,\"SHOPIFY_DEBUG\":false,\"RETENTION\":true,\"INTEGRATIONS\":true,\"PREPAID_SELLING_PLAN\":false,\"SEQUENTIAL_SELLING_PLAN\":true,\"ADVANCED_SEQUENTIAL_SELLING_PLAN\":false,\"SETUP\":false,\"LOYALTY\":false,\"BUNDLES\":false,\"TRANSLATIONS\":false,\"PASSWORDLESS\":false,\"TRENDING\":false}",
            confirmationurl: "NULL",
            trialperiodstart: 2023 - 01 - 18, T14: 29, 25.000: Z,
            trialperiodend: 2023 - 02 - 01, T14: 29, 25.000: Z,
            reportusageat: "NULL",
            is_cancelled: function () {
                return this.status === "CANCELLED";
            }
        },
        account_plan: {
            createddate: 2023 - 01 - 18, T18: 24, 25.050: Z,
            updateddate: 2023 - 01 - 18, T18: 24, 25.050: Z,
            deletedat: "NULL",
            id: "c01594fe-785a-4d6f-a449-8d30be99dd18",
            shopifyid: "NULL",
            uniqueshopifyid: "NULL",
            receivedfromshopifydate: 2023 - 01 - 18, T18: 24, 25.000: Z,
            shopifyupdatedate: 2023 - 01 - 18, T18: 24, 25.000: Z,
            planname: "Free Trial",
            status: "ACTIVE",
            approvedat: "NULL",
            trialdays: 14,
            usagelineitemshopifyid: "NULL",
            planfee: 0,
            transactionfee: 0,
            percentagefee: 0,
            organizationid: "126c230a-f07c-4416-9406-c3758b4be772",
            features: "{\"CORE_SUBSCRIPTIONS\":true,\"CORE_CONFIGURATION\":true,\"ANALYTICS\":true,\"LOOKER_ANALYTICS\":false,\"SHOPIFY_DEBUG\":false,\"RETENTION\":true,\"INTEGRATIONS\":true,\"PREPAID_SELLING_PLAN\":false,\"SEQUENTIAL_SELLING_PLAN\":true,\"ADVANCED_SEQUENTIAL_SELLING_PLAN\":false,\"SETUP\":false,\"LOYALTY\":false,\"BUNDLES\":false,\"TRANSLATIONS\":false,\"PASSWORDLESS\":false,\"TRENDING\":false}",
            confirmationurl: "NULL",
            trialperiodstart: 2023 - 01 - 18, T18: 24, 25.000: Z,
            trialperiodend: 2023 - 02 - 01, T18: 24, 25.000: Z,
            reportusageat: "NULL",
            is_cancelled: function () {
                return this.status === "CANCELLED";
            }
        },
        account_plan: {
            createddate: 2023 - 01 - 19, T01: 54, 32.393: Z,
            updateddate: 2023 - 01 - 19, T14: 57, 04: .703,
            Z: Z,
            deletedat: "NULL",
            id: "111da83a-98d0-11ed-a8fc-0242ac120002",
            shopifyid: "NULL",
            uniqueshopifyid: "NULL",
            receivedfromshopifydate: 2023 - 01 - 19, T01: 54, 32.000: Z,
            shopifyupdatedate: 2023 - 01 - 19, T01: 54, 32.000: Z,
            planname: "Grow",
            status: "ACTIVE",
            approvedat: "NULL",
            trialdays: 14,
            usagelineitemshopifyid: "NULL",
            planfee: 0,
            transactionfee: 0,
            percentagefee: 0,
            organizationid: "c535b056-fe20-4409-ab16-a4b7c5e7dff6",
            features: "{\"CORE_SUBSCRIPTIONS\":true,\"CORE_CONFIGURATION\":true,\"ANALYTICS\":true,\"LOOKER_ANALYTICS\":false,\"SHOPIFY_DEBUG\":false,\"RETENTION\":true,\"INTEGRATIONS\":true,\"PREPAID_SELLING_PLAN\":false,\"SEQUENTIAL_SELLING_PLAN\":true,\"ADVANCED_SEQUENTIAL_SELLING_PLAN\":false,\"SETUP\":false,\"LOYALTY\":false,\"BUNDLES\":false,\"TRANSLATIONS\":false,\"PASSWORDLESS\":false,\"TRENDING\":false}",
            confirmationurl: "NULL",
            trialperiodstart: 2023 - 01 - 19, T01: 54, 32.000: Z,
            trialperiodend: 2023 - 02 - 02, T01: 54, 32.000: Z,
            reportusageat: "NULL",
            is_cancelled: function () {
                return this.status === "CANCELLED";
            }
        }
    }
];
// Loop through all organizations
for (var _i = 0, organizations_1 = organizations; _i < organizations_1.length; _i++) {
    var organization = organizations_1[_i];
    // Print out the account plan name for each organization
    console.log("account plan: ".concat(organization.account_plan.planname));
}
